### PR TITLE
Use PlatformIO better

### PR DESCRIPTION
**Pull request by 2bndy5**
This pull request ("PR" for short) makes use of PlatformIO's `lib_deps` option (in the project's _platformio.ini_ file) to relieve you of having to keep copies of libraries' source code within this repository. This should optimize maintenance for this repo (& reduce the overall repo size).

## New PlatformIO build CI workflow
I added a CI (Continuous Integration) workflow (the new _.github/workflows/platformIO_build.yml_ file) that builds both _TransmitterCode_ and _ReceiverCode_ projects upon any changes to the respective source code. This new workflow (which can be observed in [this repo's "Actions" tab](https://github.com/Mmessiter/LockDownRadioControl/actions)) also saves the resulting built firmware binary files (.hex and .elf files) as ["workflow artifacts" for downloading/verifying](https://github.com/Mmessiter/LockDownRadioControl/actions/runs/1252027784#artifacts) each time the workflow is run (which is automatically triggered on push or PR events).

Please keep in mind that the artifacts (and the workflow's logs) are only available for 90 days after the workflow is run. I could arrange a more permanent solution to upload the artifacts to [published releases (of this repo)](https://github.com/Mmessiter/LockDownRadioControl/releases), but I think that would be overkill and/or unnecessary.

## All copied library dependencies removed
I have removed all copies of libraries that can be found on [PlatformIO's library registry](https://platformio.org/lib).
When a user executes (from either _ReceiverCode_ or _TransmitterCode_ directories)
```shell
pio run
```
PlatformIO ("PIO" for short) will download and install all libraries specified in the directory's _platformio.ini_ file (under the `lib_deps` option). These downloaded libs will then exist in the hidden directory _.pio/libdeps_ (which is ignored by github).

### libs that have special cases
- Notice I pinned the watchdog timer (WDT_T4) lib to the latest commit to its master branch:
   https://github.com/tonton81/WDT_T4#a5e3d3abdce1a2362562337e345524d4c953a824
   We could instead pin to the repo's master branch to automatically include any changes to the lib, but this assumes that any developmental changes on that repo does not happen in the master branch first (which I doubt is the case).
- I couldn't locate the Compress lib (a compression algorithm?) in the PIO lib registry. If it does exist in the PIO lib registry, then it can also be removed and subsequently added to the `lib_deps` option. Although, I suspect that Compress code was copied from the web somewhere.

### CODE REVIEW

**Comment by 2bndy5** [comment]
@Mmessiter Some [info on Pull Requests from the GitHub docs](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

**Comment by Mmessiter** [comment]
Wow! There's a lot there that's all new to me. Incidentally that Compress library is one I wrote myself: Because the servos are using 12 BIT resolution, their data must be stored locally in 16 BIT values with the high four BITs always zero. For transmission, these data can be compressed to ¾ of their former size with a few shifts, and zero data loss. (This is one area where high processor speed is really needed.) 
By this means I send 20 x 16 bit values compressed to only 15 (=30 bytes) - So they can fit into the nRF24L01+ max packet size.

**Comment by Mmessiter** [comment]
By the way - I just woke up as it's 07.35 AM here. (London) What time is it where you are?

**Comment by 2bndy5** [comment]
Thanks for the explanation on the Compress code. Please let me know if there were any custom modifications to the libraries I have listed as dependencies. Any custom modifications would require a local copy or a customized fork on github...

It is 11:53 PM for me (San Francisco, California, US)

**Comment by Mmessiter** [comment]
Ah! California! Thanks. 
I try to avoid editing libraries that I didn't create because the likelihood of "unintended consequences" is very high. So this is unlikely to happen - but if it does I'll mention it of course.

**Comment by 2bndy5** [comment]
traditionally, A PR must be approved before merging. This can be done by using the "review button" in the ["Files Changed" tab of the PR](https://github.com/Mmessiter/LockDownRadioControl/pull/2/files?file-filters%5B%5D=.ini&file-filters%5B%5D=.md&file-filters%5B%5D=.yml&file-filters%5B%5D=dotfile&hide-deleted-files=true&file-filters%5B%5D=.c&file-filters%5B%5D=.code-workspace&file-filters%5B%5D=.cpp&file-filters%5B%5D=.css&file-filters%5B%5D=.ex&file-filters%5B%5D=.h&file-filters%5B%5D=.ino&file-filters%5B%5D=.jpg&file-filters%5B%5D=.json&file-filters%5B%5D=.littlewire&file-filters%5B%5D=.mtl&file-filters%5B%5D=.obj&file-filters%5B%5D=.ods&file-filters%5B%5D=.old&file-filters%5B%5D=.pde&file-filters%5B%5D=.pdf&file-filters%5B%5D=.png&file-filters%5B%5D=.properties&file-filters%5B%5D=.py&file-filters%5B%5D=.sh&file-filters%5B%5D=.tpp&file-filters%5B%5D=.txt&file-filters%5B%5D=.xslt&file-filters%5B%5D=.zip&file-filters%5B%5D=No+extension).
image

I'd like to merge this before tackling a solution for #4

Furthermore, Its conventional to use the "Squash and merge" option when merging a PR. 
image
This way a branch that develops a feature with hundreds of commits can be compressed into 1 commit on the branch that the PR wants to merge into. In this case it would compress 10 commits from the "use-pio-better" branch into 1 commit on the "main" branch.

**Review by Mmessiter — APPROVED** [review]

**Comment by Mmessiter** [comment]
Not certain what it all means - but I approved it!

**Comment by 2bndy5** [comment]
don't worry. You cann tag me in any comment using `@2bndy5` to ask me to undo something... Ultimately there is nothing in this PR that changes the source code. You get a handle on the docs folder, and I'll start doing a deep dive into the source code while conforming the format.

When the docs folder is ready, I can volunteer some build firmware instructions

**Comment by Mmessiter** [comment]
Thanks. I'm hoping all will make more sense to me as I become more familiar. It's all quite a culture shock at this stage. If I do apparently foolish things (as I well might) for a while it's only because I'm floundering around in unfamiliar territory and still learning the language.

**Comment by 2bndy5** [comment]
something went wrong with this merger. I don't often see this happen, but it looks like I merged this PR at the same time that @timspray made a commit to main branch's README. The timely conflict seems to have overwritten the changes from this PR. @timspray @Mmessiter  This is an example of why people tend to work from separate branches then merge the changes into the main branch when their individual branches' goals are met.

**Pull request merged**
