### PR TITLE
Run clang format

### PR DESCRIPTION
**Pull request by Mmessiter**

### CODE REVIEW

**Comment by 2bndy5** [comment]
Is it ok if I remove the copied libs again? you just merged them back into the main branch.

**Comment by Mmessiter** [comment]
Yes thank you. I think the excess lib files can go, again, because I can test different library versions merely by editing the version number and then deleting .pio (!) 
Please correct me if I'm wrong !

**Comment by 2bndy5** [comment]
You're absolutely correct about using the version numbers. I've fixed the copied libs and ini file also. Please notice that I changed the _Compress.h_ files' includes to use `stdint.h` instead of `Arduino.h` because you only needed the definition for `uint16_t` datatype (`Arduino.h` includes `stdint.h` with a lot of other stuff that wasn't needed there).

## Please remember to update your local copy of the main branch before committing changes

**Comment by Mmessiter** [comment]
That's great thanks! Yes I now (at last - finally) realise that before making *any* edits, I must always first update my local copy in case something had changed 😄

**Comment by 2bndy5** [comment]
You're making great progress in git fu (play-on words kung fu). 😃

**Comment by Mmessiter** [comment]
Thanks! Sorry for when I'm slow, dyslexic, or just plain stupid! 

In my guts I feel warmly confident that if we continue this incremental process for a few weeks or months, we will almost inevitably end up with a super robust radio system that can be fitted with confidence into any valuable model aircraft. 

Some of my helicopters are worth more than £3,000 so the incentive for very robust control is high!

**Comment by Mmessiter** [comment]
Kung Fu Panda is one of my favourites ! 😁

**Comment by 2bndy5** [comment]
I'm also waiting for ideal integration of the new RP2040 chip into PIO's platforms (it is limited to only 2 boards right now). Then I'll start bugging you about supporting a feather board layout on the custom PCB (there's a teesny to feather adapter board from adafruit too). This way the MCU could be interchangeable (not limited to just the teensy). Although, before we even get there, I plan on getting #8 fixed and helping you optimize the code as it becomes more stable. I usually get suckered into terrain-based robotics projects, so this drone stuff is a cool step forward for me.

**Comment by Mmessiter** [comment]
That's fascinating - and excellent news!

Yes the future of this project is big. 

If we get it working for example on ESP32 (etc) MCUs, we might add wifi support. Then perhaps add an iOS and/or Android app that allows all configuration from a smartphone.

It'd be good to replace the Nextion one day with something more visible in sunshine. 

The integrated screen could be dropped altogether if a smartphone were to take over that rôle.

And then there is of course PID, GPS, 
... Autonomy! 🤔😃

**Comment by 2bndy5** [comment]
>Autonomy!

I've never been successful at adding autonomy to a robotics project 😞. You may need to lean on someone else with more experience in that arena. I have been able to add orientation (a lot of work in itself), but terrain-based robots have a lot more obstacles than I imagine a drone would have to deal with.

**Comment by Mmessiter** [comment]
I think it's all possible. But quite a challenge. 
As you say, up in the air there's much less to collide with if you're high enough! 

On the ground it's **VERY** hard ... as Elon Musk is currently finding.

**Comment by Mmessiter** [comment]
Which line should I remove?

**Comment by 2bndy5** [comment]
https://github.com/Mmessiter/LockDownRadioControl/commit/16804ee1e820855e0cbf4764a8a83872820bf1c2#r57072934

**Pull request merged**
