### PR TITLE
Project updates

### PR DESCRIPTION
**Pull request by 2bndy5**
I've been going through and cleaning up my local repositories and found that my copy of this one needed attention.

## So, here is what I did:
- removes copies of dependencies that can be downloaded by PIO during build
- update the SensorHubT32 projects platformio.ini about dependencies
- remove BMP380 dependency from ReceiverCode project
- remove adafruitGPS lib from ReceiverCode project's lib folder
- update the vscode workspace file for the renamed "SD card" folder and add SensorHubT32 project into the workspace
- add clang-format config for SensorHubT32 project
- updated the CI workflows
- reduced the Doxygen config (titled Doxyfile) to only what is needed (everything removed was all default or not used)

### Notes
The ReceiverCode still uses INA219 lib, but I'm not sure if that's needed now that the SensorHubT32 project now uses that sensor. Thoughts?

### Requests to admin
Please enable the github pages feature for this repo.
1. Go into the repo settings, and open the "Pages" section from the side bar
   - Or go to https://github.com/Mmessiter/LockDownRadioControl/settings/pages
2. Select the "gh-pages" branch and use the root folder
   image
3. After clicking "Save", the docs (being built by the CI) should be hosted at https://Mmessiter.github.io/LockDownRadioControl/

### CODE REVIEW

**Comment by Mmessiter** [comment]
Wow!! 😳

I’ll go through in detail later. I can answer one question right now:

Yes INA219 is still needed for the receiver because when the sensor hub is omitted, many users will still want to know receiver battery state. It’s important. 
So both routes are enabled.

I better do a serious pull ! 😂

With all best wishes 

Malcolm

**Comment by 2bndy5** [comment]
> Good control to the limits of eyesight at least.

WOW! That's freaking impressive! 🎉 

> Cheap buck convertors emit a lot of RF noise!!

That is interesting. My first guess is cheaply sourced capacitors, but there may be something else going on with the PCB layout.

The cheap nRF24L01+PA/LNA modules people keep buying on Amazon often need a Faraday cage to isolate from electromagnetic interference. Instead of telling people to buy a Faraday cages (which can be pricey for the size of the radio), I often suggest a home-brew  solution that involves a layer of electrical tape around the module and aluminum foil around the layer of electrical tape.
- the electrical tape keeps current carrying parts from touching the aluminum foil.
- the aluminum foil does the electromagnetic blocking
- sometimes results are better when the shielding is tied to ground, but that hasn't been my experience with cheap nRF24L01+PA/LNA modules

The ebyte modules you're using seem to already have electromagnetic shielding, but it may not be enough when positioned near a strong source of RF noise.

**Comment by Mmessiter** [comment]
Yes you’re right!! 

Home made cooking foil wrapping seems the best way. My mistake was locating the receiver aerial much too close to the buck convertor !!!  Stupid of me.

Because car theft can now be achieved by cloning RF from ‘keys’ I keep car keys and credit cards similarly shielded now! 

The DJI Flamewheel 550 was best range test ! The autopilot will just return it to start and land if the radio fails. But I flew it out of sight without loss of signal !

Now I can log all data in real time I’ll repeat these tests ….

**Comment by 2bndy5** [comment]
@Mmessiter I would prefer you merge this (or squash and merge this) _before_ adding more changes to the main branch. Every time you commit to main, I have to resolve merge conflicts on the branch that has these changes (which isn't easy - even for me).

**Comment by Mmessiter** [comment]
For a long time I’ve developed the code only in the main branch. I’ve not touched any other branch at all. I didn’t even know any existed. So I don’t know what you mean. There’s still much detail in GitHub’s inner workings that I’ve never used or understood. I’ve prioritized the code itself rather than GitHub functions. So perhaps I’ve missed something? I do occasionally receive weird notifications from GitHub that I don’t understand. But it’s so far always been a very useful and reliable place  to share the code.!

**Comment by 2bndy5** [comment]
[You have 3 branches](https://github.com/Mmessiter/LockDownRadioControl/branches).
1. You've been using as the default branch titled "main" (this is what everyone sees when looking for the _most stable_ code base.
2. I created a branch titled "gh-pages" which is devoted to holding the generated website (HTML, CSS, & JS files) that can be used for many things. In this case the website files are the technical documentation (including the MD files in the Docs folder). The steps I outlined in this thread's first comment/description will enable free hosting of said website files.
3. Any other branches are like private workspaces for team members. For this Pull Request, I created a branch called "project-updates" (branch names can't have spaces). Non-default branches are often used to develop specific features of the project, then merged into the default ("main") branch when ready.

When you merge a pull request from one branch to another/target branch, all the changes exist on the target branch. In this case (and very often), the target branch is the "main" branch.

But every time you push a commit to the "main" branch, I have to update my "project-updates" branch so that github can merge the changes. It is pretty common with large changes (like with this Pull Request) that github gets confused on how to merge branches when the history for each branch is concurrently active (commit chronology is important in this process).

**Comment by 2bndy5** [comment]
I have been using [gitkraken](https://www.gitkraken.com/) lately to better manage my git history. It comes with some pretty nice features like visualization of branch history.
image

**Comment by Mmessiter** [comment]
This was unknown to me! Thank you! It seems to me to be unnecessarily complex.

Maybe it might be better in this case to simplify things and reduce all into a single main branch - because I think no one but me is developing the code?

**Comment by 2bndy5** [comment]
> It seems to me to be unnecessarily complex

In your case it kinda is because you're mostly working alone. However, imagine you have the best known -good state of code on main, and you want to add an experimental feature (like rover support with mecanum wheels) without losing the best known-good state of code. Instead of relying on an undo button, you can just switch to a different branch and work without consequences.

If you have nothing to commit, I'll merge this (its mostly whitespace changes in the code)

**Comment by 2bndy5** [comment]
Github has docs about branch managment [using Github Desktop app](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches)

**Comment by 2bndy5** [comment]
Can I merge this? Afterward, you'll have to pull the changes to main branch before committing anything.

**Comment by Mmessiter** [comment]
I’ll look at gitkraken!

**Comment by 2bndy5** [comment]
I've reverted all changes to the code in src folders and updated them to what is in the current main branch. This should help keep this project-updates branch up-to-date with the constant flow of changes to the main branch.

**Comment by Mmessiter** [comment]
Yes merge! I’ve made copies just to be safe but I’m confident you only ever improve things!!!

**Comment by 2bndy5** [comment]
If there are problems then let me know.

**Comment by Mmessiter** [comment]
I cannot yet compile the version you just pushed. The error message said “you’ve not yet agree to the Xcode terms and conditions” or something like that. I’d happily agree if I knew how!! 😁Sent from Malcolm's iPhoneOn 11 Oct 2022, at 08:55, Brendan ***@***.***> wrote:﻿
If there are problems then let me know.

**Comment by 2bndy5** [comment]
It sounds like an update to the mac C++ compiler requires your attention. I can't help with that as I don't work with any apple products. I'm not surprised that Apple attached a privacy agreement to their C++ compiler (which ships with Xcode app/IDE I think).

**Comment by Mmessiter** [comment]
Perhaps I should run Xcode and agree?! Sent from Malcolm's iPhoneOn 11 Oct 2022, at 09:18, Brendan ***@***.***> wrote:﻿
It sounds like an update to the mac C++ compiler requires your attention. I can't help with that as I don't work with any apple products. I'm not surprised that Apple attached a privacy agreement to their C++ compiler (which ships with Xcode app/IDE I think).

**Comment by 2bndy5** [comment]
Yeah, I assume the Xcode app should have an alert of some kind when you open it.

**Comment by Mmessiter** [comment]
… but last nights version still compiles without problem so I’m puzzled 🤔! Sent from Malcolm's iPhoneOn 11 Oct 2022, at 09:18, Brendan ***@***.***> wrote:﻿
It sounds like an update to the mac C++ compiler requires your attention. I can't help with that as I don't work with any apple products. I'm not surprised that Apple attached a privacy agreement to their C++ compiler (which ships with Xcode app/IDE I think).

**Comment by 2bndy5** [comment]
I just pushed the update for the CI workflows to main branch. I could open another PR to have the build CI workflow use Linux, Windows, and macOS. But, I think it would be a bit redundant because PlatformIO uses python to drive the compilation (which is a rather platform agnostic).

**Comment by Mmessiter** [comment]
Indeed. I Just opened Xcode and ‘agreed’ to everything… now it’s downloading lots of extras so I better wait a moment… Sent from Malcolm's iPhoneOn 11 Oct 2022, at 09:23, Brendan ***@***.***> wrote:﻿
Yeah, I assume the Xcode app should have an alert of some kind when you open it.

**Comment by 2bndy5** [comment]
Good to hear! I had to push another CI update about the python version used in the CI. I should be done pushing commits to main now.

**Comment by Mmessiter** [comment]
Good morning Brendan!

I am not sure what that means exactly but thank you! 😊

Incidentally, the other day I implemented an idea to speed up recovery after a single lost data packet: 

After losing a single packet, both ends now immediately hop to the next frequency in the FHSS array. In the presence of wifi or other RC transmitters a lost packet probably means a frequency collision, so a rapid change of frequency stands a good chance of fixing things quickly. Seems to work!

I also have started to explore Nick Rehm’s code  for vtol stabilisation (https://github.com/nickrehm/dRehmFlight)

Since my radio comms code seems pretty robust now, I thought this might be a good route to stabilisation because Nick’s maths is far better than mine! I’ll modify bits until I get it working - on a separate Teensy 4.0. Then perhaps the modified version should be added to our repo.

Gains and other parameters are currently hard coded. I’ll make these adjustable from our transmitter using channels than were not needed.

With all best wishes 

Malcolm

**Comment by 2bndy5** [comment]
Cool! I agree about the fast channel hop. I think that's the same way WiFi works.

**Comment by Mmessiter** [comment]
I’ll try a new PULL in a moment and if it compiles now!By the way, the latest version (1.9.4) is working really well now.  It seems robust and safe with big expensive models. I’m using it all the time as are a few friends. I’ve added some features which I ought to write about more:Model memory match: this feature saves the MAC address of the receiver Teensy in the model memory. It also saves the MAC address of the TX in the RX eeprom. Then to avoid accidentally trying to fly a model with the wrong memory loaded, interesting things happen at connect time: both ends expose their local MAC address to the other. These are checked. If the model memory is the wrong one, the tx searches and if it exists it loads the correct one!! If both match, connection completes and flying is possible. If either fails, the user is asked to rebind. I also added a motor safety switch. If off motor will not start. Simple but safer. Interesting to implement!… etc.I know your hardware will not run latest version. I could send you the latest hardware if you think you might use it!With all best wishes Malcolm  Sent from Malcolm's iPhoneOn 11 Oct 2022, at 09:47, Brendan ***@***.***> wrote:﻿
Cool! I agree about the fast channel hop. I think that's the same way WiFi works.

**Comment by Mmessiter** [comment]
Transmitter code now compiles ok again!Receiver code gives errors …Sent from Malcolm's iPhoneOn 11 Oct 2022, at 09:47, Brendan ***@***.***> wrote:﻿
Cool! I agree about the fast channel hop. I think that's the same way WiFi works.

**Comment by 2bndy5** [comment]
I'll look into the RX code tomorrow, its getting late here. I suspect that there are multiple/various copies of the libraries on your local machine (again). This PR simply removed some copied libraries in favor of using the platformio.ini config.

**Comment by Mmessiter** [comment]
Thanks Brendan! No rush. Tomorrow is fine!!Sent from Malcolm's iPhoneOn 11 Oct 2022, at 10:29, Brendan ***@***.***> wrote:﻿
I'll look into the RX code tomorrow, its getting late here. I suspect that there are multiple/various copies of the libraries on your local machine (again). This PR simply removed some copied libraries in favor of using the platformio.ini config.

**Comment by Mmessiter** [comment]
… I’ll do a test without any local libraries…. Sent from Malcolm's iPhoneOn 11 Oct 2022, at 10:29, Brendan ***@***.***> wrote:﻿
I'll look into the RX code tomorrow, its getting late here. I suspect that there are multiple/various copies of the libraries on your local machine (again). This PR simply removed some copied libraries in favor of using the platformio.ini config.

**Comment by Mmessiter** [comment]
I noticed I’d been using the rf24 library v. 1.4.1 and you added a later version. Which version is the latest Safe to Use version ?Sent from Malcolm's iPhoneOn 11 Oct 2022, at 10:29, Brendan ***@***.***> wrote:﻿
I'll look into the RX code tomorrow, its getting late here. I suspect that there are multiple/various copies of the libraries on your local machine (again). This PR simply removed some copied libraries in favor of using the platformio.ini config.

**Comment by Mmessiter** [comment]
… there were no local libraries for me to remove …Sent from Malcolm's iPhoneOn 11 Oct 2022, at 13:34, Malcolm Messiter ***@***.***> wrote:﻿I noticed I’d been using the rf24 library v. 1.4.1 and you added a later version. Which version is the latest Safe to Use version ?Sent from Malcolm's iPhoneOn 11 Oct 2022, at 10:29, Brendan ***@***.***> wrote:﻿
I'll look into the RX code tomorrow, its getting late here. I suspect that there are multiple/various copies of the libraries on your local machine (again). This PR simply removed some copied libraries in favor of using the platformio.ini config.

**Comment by 2bndy5** [comment]
v1.4.6 is now the latest. The only relevant changes are about the internal definitions of some macros (when not provided in avrspace.h by the teensyduino core).

v1.4.4 should be avoided because it has a known bug from when we introduced `sprintf()` support

**Comment by Mmessiter** [comment]
Thanks !!! Sent from Malcolm's iPhoneOn 11 Oct 2022, at 18:57, Brendan ***@***.***> wrote:﻿
v1.4.6 is now the latest. The only relevant changes are about the internal definitions of some macros (when not provided in avrspace.h by the teensyduino core).
v1.4.4 should be avoided because it has a known bug from when we introduced sprintf() support

**Comment by 2bndy5** [comment]
I had some problems at first... I'm now able to compile the RX code after
1. updating the PlatformIO core
2. deleting the ReceiverCode/.pio folder

You should see PIO re-download everything it needs to compile (which takes about 30 seconds). But afterward it should compile.

It might be a good idea to delete the other .pio folders in TransmitterCode and SensorHubT32) if the PIO core was actually updated on your machine.

**Comment by Mmessiter** [comment]
Thanks very much Brendan! I’ll try this in the morning as we are in a restaurant right now 😁! With all best wishes Malcolm Sent from Malcolm's iPhoneOn 11 Oct 2022, at 19:31, Brendan ***@***.***> wrote:﻿
I had some problems at first... I'm now able to compile the RX code after

updating the PlatformIO core
deleting the ReceiverCode/.pio folder

You should see PIO re-download everything it needs to compile (which takes about 30 seconds). But afterward it should compile.
It might be a good idea to delete the other .pio folders in TransmitterCode and SensorHubT32) if the PIO core was actually updated on your machine.

**Comment by Mmessiter** [comment]
I did it and it works now !! 😁👍Sent from Malcolm's iPhoneOn 11 Oct 2022, at 19:31, Brendan ***@***.***> wrote:﻿
I had some problems at first... I'm now able to compile the RX code after

updating the PlatformIO core
deleting the ReceiverCode/.pio folder

You should see PIO re-download everything it needs to compile (which takes about 30 seconds). But afterward it should compile.
It might be a good idea to delete the other .pio folders in TransmitterCode and SensorHubT32) if the PIO core was actually updated on your machine.

**Pull request merged**
